#This playbook installs the bitnami Wordpress chart in the cluster
- name: Install bitnami Wordpress
  hosts: localhost
  tasks:
    - name: Logging in to Azure account
      command: "az login"

    - name: Getting access to AKS cluster
      command: "az aks get-credentials --name wpk8saks --resource-group wpk8s --overwrite-existing"
      
    - name: Add Bitnami to helm repo      
      command: "helm repo add bitnami https://charts.bitnami.com/bitnami"

      name: Add Elastic to helm repo
      command: "helm repo add elastic https://helm.elastic.co/"

    - name: Helm repo update
      command: "helm repo update"
    
    - name: Deploy bitnami wordpress helm chart
      command: "helm install wordpress -f wordpress_config.yaml bitnami/wordpress"